name: COLMAP (Docker)

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  release:
    types: [ published, edited ]

env:
  IS_RELEASE: ${{ github.event_name == 'release' || startsWith(github.ref, 'refs/tags') }}
  FETCHCONTENT_CACHE_VERSION: 1
  FETCHCONTENT_CACHE_DIR: build/_deps
  COMPILER_CACHE_VERSION: 1
  CCACHE_DIR: build/.ccache

jobs:
  build:
    name: ubuntu-24.04
    runs-on: ubuntu-24.04
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4

      - name: Restore FetchContent cache
        uses: actions/cache@v4
        id: cache-fetchcontent
        with:
          key: fetchcontent-v${{ env.FETCHCONTENT_CACHE_VERSION }}-docker-${{ hashFiles('cmake/FindDependencies.cmake', 'src/thirdparty/CMakeLists.txt') }}
          restore-keys: fetchcontent-v${{ env.FETCHCONTENT_CACHE_VERSION }}-docker-
          path: ${{ env.FETCHCONTENT_CACHE_DIR }}

      - name: Restore compiler cache
        uses: actions/cache@v4
        id: cache-ccache
        with:
          key: ccache-v${{ env.COMPILER_CACHE_VERSION }}-docker-${{ github.run_id }}
          restore-keys: ccache-v${{ env.COMPILER_CACHE_VERSION }}-docker-
          path: ${{ env.CCACHE_DIR }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ env.IS_RELEASE == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          dockertag=$(date +%Y%m%d).${{ github.run_number }}
          if [[ "${{ env.IS_RELEASE }}" == "true" ]]; then
            cuda_archs="50;60;70;75;90"
          else
            cuda_archs="50"
          fi
          docker build . \
            --file docker/Dockerfile \
            --tag colmap/colmap:$dockertag \
            --build-arg CUDA_ARCHITECTURES="$cuda_archs" \
            --build-arg FETCHCONTENT_FULLY_DISCONNECTED=${{ steps.cache-fetchcontent.outputs.cache-hit == 'true' && 'ON' || 'OFF' }}
          if [[ "${{ env.IS_RELEASE }}" == "true" ]]; then
            docker tag colmap/colmap:$dockertag colmap/colmap:latest
            docker push colmap/colmap:$dockertag
            docker push colmap/colmap:latest
          fi

      - name: Cleanup compiler cache
        run: |
          set -x
          sudo apt-get install -y ccache
          ccache --show-stats --verbose
          ccache --evict-older-than 1d
          ccache --show-stats --verbose
